---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: to-do-api-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-api
  analysis:
    successfulRunHistoryLimit: 2
    unsuccessfulRunHistoryLimit: 2
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: cpu-rate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: to-do-api
    spec:
      containers:
        - image: to-do-api
          name: to-do-api
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /api/healthz/ready
              port: 8080
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            httpGet:
              path: /api/healthz/alive
              port: 8080
          env:
            - name: DB_HOST
              value: db-svc
            - name: DB_PORT
              value: "5432"
            - name: DB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: POSTGRES_USER
                  optional: false
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: POSTGRES_DB
                  optional: false

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: to-do-web-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-web
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: cpu-rate
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        app: to-do-web
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
      containers:
        - image: to-do-web
          imagePullPolicy: Always
          name: to-do-web
          readinessProbe:
            initialDelaySeconds: 90
            periodSeconds: 20
            httpGet:
              path: /todo/api/healthz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 20
            httpGet:
              path: /todo/test.xhtml
              port: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "300Mi"
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/local_files/images
          env:
            - name: UPLOAD_LOCATION
              value: "/usr/src/app/local_files/images/to-do-today.jpg"
            - name: TODO_API_URI
              value: "http://to-do-api-svc:2345/api/todos"
            - name: TODO_API_HEALTH_URI
              value: "http://to-do-api-svc:2345/api/healthz/ready"
